### Connexion John Doe
POST http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email = john@doe.com &
password = azerty

### Connexion jane Doe
POST http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email = jane@doe.com &
password = qwerty

### Connexion Mario Bros
POST http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email = mario@nintendo.com &
password = 1234


### Fail Connexion Mario Bros
POST http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email = mario@nintendo.com &
password = 5678